# Playbook for [web]
---
- hosts: web # name of the host
  gather_facts: yes  # gather facts about the installation steps
  become: true # admin access

  # instructions to install nginx:
  tasks:
  - name: Install Nginx
    apt: pkg=nginx state=present
