---
- hosts: db
  gather_facts: yes
  become: true

  tasks:
  - name: Install MongoDB
    shell: |
      wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
      sudo apt-get update -y
      sudo apt-get install -y mongodb-org
      sudo systemctl start mongod
      sudo systemctl enable mongod

  - name: Running MongoDB Playbook
    import_playbook: copy_mongo_conf.yml

